
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_GPIO_AUDIO_BUTTONS_DEVICE_ID,
		XPAR_GPIO_AUDIO_BUTTONS_BASEADDR,
		XPAR_GPIO_AUDIO_BUTTONS_INTERRUPT_PRESENT,
		XPAR_GPIO_AUDIO_BUTTONS_IS_DUAL
	},
	{
		XPAR_GPIO_SWITCHES_DEVICE_ID,
		XPAR_GPIO_SWITCHES_BASEADDR,
		XPAR_GPIO_SWITCHES_INTERRUPT_PRESENT,
		XPAR_GPIO_SWITCHES_IS_DUAL
	},
	{
		XPAR_GPIO_VGA_BUTTONS_DEVICE_ID,
		XPAR_GPIO_VGA_BUTTONS_BASEADDR,
		XPAR_GPIO_VGA_BUTTONS_INTERRUPT_PRESENT,
		XPAR_GPIO_VGA_BUTTONS_IS_DUAL
	}
};


